--- #YAML:1.0
name:               Test-WWW-Selenium-ExtJS
version:            0.0.1
abstract:           Testing ExtJS powered gui with selenium
author:
    - Mario Minati <mario.minati@minati.de>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Readonly:       0
    Test::More:     0
    Time::HiRes:    0
    version:        0
    WWW::Selenium:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
